### ISSUE TITLE
Fail to import

### ISSUE THREAD

**Issue by muteboy** [signmotion/graphviz-syntax-highlighting#1]
Downloaded to Desktop, in Notepad++ > Language > Define your language > Import > browse to file. Clicked OK, error message "Fail to import.". No other information.

Notepad++ v7.5.7   (64-bit)
Build time : Jun 29 2018 - 00:53:58
Path : C:\Program Files\Notepad++\notepad++.exe
Admin mode : OFF
Local Conf mode : OFF
OS : Windows 10 (64-bit)
Plugins : DSpellCheck.dll mimeTools.dll NppConverter.dll

**Comment by syrokomskyi** [comment]
Attempt today's fix.

**Comment by muteboy** [comment]
Imports fine now, thanks! I think I may have downloaded the wrong file from github - I right-clicked and saved.
